version: '3.7'

services:
  web:
    build: ./organizer
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./organizer/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./organizer/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=skillhq
      - POSTGRES_PASSWORD=skillhq
      - POSTGRES_DB=skillhq_dev

volumes:
  postgres_data: